### ISSUE TITLE
should be binNum.substr

### ISSUE THREAD

**Issue by msk86** [ymssx/yugioh-card#2]
https://github.com/ymssx/yugioh-card/blob/5b8d2d732a8915afdf5cf0a91122f5394f1d4cd3/source/lib/variation.js#L94
or you can simply use `num & 0xF`;

https://github.com/ymssx/yugioh-card/blob/5b8d2d732a8915afdf5cf0a91122f5394f1d4cd3/source/lib/variation.js#L113
toon is `kt` not `tk`

**Comment by ymssx** [comment]
thanks！
